name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, riscv64gc-unknown-linux-gnu
        components: rustfmt, clippy
    - name: Rust Version
      run: rustup --version && rustc --version
    - name: Run clippy x86_64
      run: cargo clippy --verbose --target x86_64-unknown-linux-gnu --all-features -- -D warnings
    - name: Run clippy aarch64
      run: cargo clippy --verbose --target aarch64-unknown-linux-gnu --all-features -- -D warnings
    - name: Run clippy riscv64
      run: cargo clippy --verbose --target riscv64gc-unknown-linux-gnu --all-features -- -D warnings
    - name: Reformat code
      uses: mbrobbel/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
