name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, clippy
    - name: Install Targets
      run: rustup target add x86_64-unknown-none aarch64-unknown-none riscv64gc-unknown-none-elf loongarch64-unknown-none
    - name: Rust Version
      run: rustup --version && rustc --version
    - name: Run clippy x86_64
      run: cargo clippy --verbose --target x86_64-unknown-none --all-features -- -D warnings
    - name: Run clippy aarch64
      run: cargo clippy --verbose --target aarch64-unknown-none --all-features -- -D warnings
    - name: Run clippy riscv64
      run: cargo clippy --verbose --target riscv64gc-unknown-none-elf --all-features -- -D warnings
    - name: Run clippy loongarch64
      run: cargo clippy --verbose --target loongarch64-unknown-none --all-features -- -D warnings
    - name: Reformat code
      uses: mbrobbel/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
